// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmnibusUI.Data;

#nullable disable

namespace OmnibusUI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104161038_AddBookhouseTable")]
    partial class AddBookhouseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmnibusUI.Models.Book", b =>
                {
                    b.Property<string>("bookID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("authorFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("authorLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("avgRating")
                        .HasColumnType("real");

                    b.Property<int>("copiesAvail")
                        .HasColumnType("int");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("isDigital")
                        .HasColumnType("int");

                    b.Property<int>("numPages")
                        .HasColumnType("int");

                    b.Property<string>("publicationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bookID");

                    b.ToTable("Bookhouse");
                });

            modelBuilder.Entity("OmnibusUI.Models.Patron", b =>
                {
                    b.Property<string>("patronID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("booksBorrowwed")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("libCardNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("patronID");

                    b.ToTable("Patrons");
                });
#pragma warning restore 612, 618
        }
    }
}
