// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmnibusUI.Data;

#nullable disable

namespace OmnibusUI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmnibusUI.Models.Author", b =>
                {
                    b.Property<int>("authID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("authID"));

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("authID");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("OmnibusUI.Models.Book", b =>
                {
                    b.Property<string>("isbn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("authorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("avgRating")
                        .HasColumnType("float");

                    b.Property<int>("copiesAvail")
                        .HasColumnType("int");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDigital")
                        .HasColumnType("bit");

                    b.Property<int>("numPages")
                        .HasColumnType("int");

                    b.Property<DateOnly>("publicationDate")
                        .HasColumnType("date");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("isbn");

                    b.ToTable("Bookhouse");
                });

            modelBuilder.Entity("OmnibusUI.Models.LibraryCard", b =>
                {
                    b.Property<string>("libCardNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("booksBorrowed")
                        .HasColumnType("int");

                    b.Property<DateOnly>("expDate")
                        .HasColumnType("date");

                    b.Property<double>("fines")
                        .HasColumnType("float");

                    b.Property<DateOnly>("issueDate")
                        .HasColumnType("date");

                    b.HasKey("libCardNum");

                    b.ToTable("LibraryCards");
                });

            modelBuilder.Entity("OmnibusUI.Models.Patron", b =>
                {
                    b.Property<string>("libCardNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("homeAddress")
                        .HasColumnType("int");

                    b.Property<string>("userFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("libCardNum");

                    b.ToTable("Patrons");
                });

            modelBuilder.Entity("OmnibusUI.Models.Test", b =>
                {
                    b.Property<string>("bookID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("authorFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("authorLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bookID");

                    b.ToTable("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
